language: php


branches:
  only:
    - master

env:
  global:
    - secure: QYfbRlo0zvZH+u6LSZrrRJ7m2kD1u5Uj8FyU18tH/SybbS06uASMTbq873vwG9gV38MIftPkWLrTM+YNYseecvR+zlu/PnXy3MW4miLsOoiZvfhSJu7eDD8DsRQKcYnRqgz1DPkNSOc34kI/VpKw/+ZGj5429dQc2Ni1jkCb5xBe1mo2iTYr86Bzr6KNaULMoiwxVvc3jvi8btOidgMWCEMOvFvBgzHYENSwwSsiCmXGyRwNeMhxwynN6E3bmCXKe4ekMpzBr7ghMdhcUlCBzUUTpVymahWOEysp2el2ScHskmbE5H3iP/Bw8v5cu/8zmSj1yPk3VmEt+Oo85/zhHw==
    - GCR_BASE="eu.gcr.io/$MY_ORG"
    - IMAGE_TAG="${BRANCH}.${BUILD_NUMBER}"
    - NGINX_IMAGE_NAME="nginx-test"
    - PHP_IMAGE_NAME="php-test"
    - NGINX_IMAGE="${GCR_BASE}/${NGINX_IMAGE_NAME}:${IMAGE_TAG}"
    - PHP_IMAGE="${GCR_BASE}/${PHP_IMAGE_NAME}:${IMAGE_TAG}"

build:
  ci:
    - cp nginx-Dockerfile Dockerfile 
    - docker build -t "$NGINX_IMAGE" . 
    - cp php-Dockerfile Dockerfile
    - docker build -t "$PHP_IMAGE" .
    - docker push "$NGINX_IMAGE"
    - docker push "$PHP_IMAGE"
    - sed -i '/versionName/d' $JOB_STATE/php-image.env ; echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/php-image.env
    - sed -i '/versionName/d' $JOB_STATE/nginx-image.env ; echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/nginx-image.env
    - sed -i '/sourceName/d' $JOB_STATE/nginx-image.env ; echo "sourceName=$GCR_BASE/$NGINX_IMAGE_NAME" >> $JOB_STATE/nginx-image.env
    - sed -i '/sourceName/d' $JOB_STATE/php-image.env ; echo "sourceName=$GCR_BASE/$$PHP_IMAGE_NAME" >> $JOB_STATE/nphp-image.env

integrations:
  hub:
    - integrationName: gcloud-integration    #replace with your subscription integration name
      type: gcloudKey

resources:
  - name: nginx-image
    type: image
    integration: gcloud-integration    #replace with your Docker Hub integration name
    pointer:
      sourceName: $GCR_BASE/$NGINX_IMAGE_NAME  #replace with your image name on Docker Hub
    seed:
      versionName: "master.1"  #replace with your image tag on Docker Hub
    flags:
      - php-test-new

  - name: php-image
    type: image
    integration: gcloud-integration
    pointer:
      sourceName: $GCR_BASE/$PHP_IMAGE_NAME
    seed:
      versionName: "master.1"
    flags:
      - php-test-new

#kubernetes cluster
  - name: gke-cluster
    type: cluster
    integration: gcloud-integration    #replace with your Kubernetes integration name
    pointer:
      sourceName: "test-cluster"
      region: "europe-west1-d"
      namespace: "test"
    flags:
     - php-test-new

jobs:
  - name: php-test-new_runCI
    type: runCI
    flags:
      - php-test-new
    steps:
      - OUT: nginx-image
      - OUT: php-image

  - name: app-manifest
    type: manifest
    flags:
      - php-test-new
    steps:
     - IN: php-image
     - IN: nginx-image

  - name: deploy
    type: deploy
    flags:
      - php-test-new
    steps:
      - IN: app-manifest
      - IN: gke-cluster
