language: php


branches:
  only:
    - master

env:
  global:
    - secure: Yk7231s0euUDsS4An/05ImAFdUrFw8PVjCLB1CBpa9Gzq15j2T2A7npJxYyoy1QBmltffd7sxFqH98w/x4ooyz6AUyyG+l3XreN+/V1OqxUqmeHpHGhXoxxTF1WXo/NTHUBH9sLZtBMd6CCOUOlTZ+5mTV6Y4Grd9GNCAtfOj85uu5/Co01O3xAygBFTuO3bF/SuVopuWehXrtMPTY1DN9Rfz6uQ7Mw240RW7BLHQcm0VVVauVmzoiKAIXNKbfViyIeRtZixGHcAg4LO9UWQed7YCcBO9gbT9gPJvhGctoG/5lYiS10peqQfueif83YaNNsJBNZ8RVqAhFq/iXzDZQ==
    - GCR_BASE="eu.gcr.io/$MY_ORG"
    - IMAGE_TAG="${BRANCH}.${BUILD_NUMBER}"
    - NGINX_IMAGE_NAME="nginx-test"
    - PHP_IMAGE_NAME="php-test"
    - NGINX_IMAGE="${GCR_BASE}/${NGINX_IMAGE_NAME}:${IMAGE_TAG}"
    - PHP_IMAGE="${GCR_BASE}/${PHP_IMAGE_NAME}:${IMAGE_TAG}"

build:
  ci:
    - cp nginx-Dockerfile Dockerfile 
    - docker build -t "$NGINX_IMAGE" . 
    - cp php-Dockerfile Dockerfile
    - docker build -t "$PHP_IMAGE" .
    - docker push "$NGINX_IMAGE"
    - docker push "$PHP_IMAGE"
    - echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/php-test-new-nginx-image.env
    - echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/php-test-new-php-image.env
integrations:
  hub:
    - integrationName: gcloud-integration    #replace with your subscription integration name
      type: gcloudKey

resources:
  - name: php-test-new-nginx-image
    type: image
    integration: gcloud-integration    #replace with your Docker Hub integration name
    pointer:
      sourceName: "${GCR_BASE}/${NGINX_IMAGE_NAME}"  #replace with your image name on Docker Hub
    seed:
      versionName: "master.1"  #replace with your image tag on Docker Hub
    flags:
      - php-test-new

  - name: php-test-new-php-image
    type: image
    integration: gcloud-integration
    pointer:
      sourceName: "${GCR_BASE}/${PHP_IMAGE_NAME}"
    seed:
      versionName: "master.1"
    flags:
      - php-test-new

#kubernetes cluster
  - name: mc-kube-cluster
    type: cluster
    integration: gcloud-integration    #replace with your Kubernetes integration name
    pointer:
      sourceName: "$GKE_CLUSTER_NAME"
      region: "europe-west1-d"
      namespace: "test"
    flags:
     - php-test-new

jobs:
  - name: test
    type: runSh
    triggerMode: parallel
    steps:
      - TASK:
        - script: echo hello

  - name: php-test-new_runCI
    type: runCI
    flags:
      - php-test-new
    steps:
      - OUT: php-test-new-nginx-image
      - OUT: php-test-new-php-image

  - name: php-test-new-manifest-1
    type: manifest
    flags:
      - php-test-new
    steps:
     - IN: php-test-new-php-image
     - IN: php-test-new-nginx-image

  - name: dkmc-deploy-1
    type: deploy
    flags:
      - php-test-new
    steps:
      - IN: php-test-new-manifest-1
      - IN: mc-kube-cluster
