language: php

branches:
  only:
    - master
    - development
    - release/*
  except:
    - feat*

env:
  global:
    - secure: QYfbRlo0zvZH+u6LSZrrRJ7m2kD1u5Uj8FyU18tH/SybbS06uASMTbq873vwG9gV38MIftPkWLrTM+YNYseecvR+zlu/PnXy3MW4miLsOoiZvfhSJu7eDD8DsRQKcYnRqgz1DPkNSOc34kI/VpKw/+ZGj5429dQc2Ni1jkCb5xBe1mo2iTYr86Bzr6KNaULMoiwxVvc3jvi8btOidgMWCEMOvFvBgzHYENSwwSsiCmXGyRwNeMhxwynN6E3bmCXKe4ekMpzBr7ghMdhcUlCBzUUTpVymahWOEysp2el2ScHskmbE5H3iP/Bw8v5cu/8zmSj1yPk3VmEt+Oo85/zhHw==
    - GCR_BASE="eu.gcr.io/$MY_ORG"
    - IMAGE_TAG="${BRANCH}.${BUILD_NUMBER}"
    - NGINX_IMAGE_NAME="nginx-test"
    - PHP_IMAGE_NAME="php-test"
    - NGINX_IMAGE="${GCR_BASE}/${NGINX_IMAGE_NAME}:${IMAGE_TAG}"
    - PHP_IMAGE="${GCR_BASE}/${PHP_IMAGE_NAME}:${IMAGE_TAG}"
build:
  ci:
    # composer install --no-interaction --optimize-autoloader
    # npm install --unsafe-perm
    # ./vendor/bin/test -p php ...
    # ./vendor/bin/phpstan
    # ./vendor/bin/phpcs
    - echo 'ci done'
  post_ci:
    - cp nginx-Dockerfile Dockerfile 
    - docker build -t "$NGINX_IMAGE" . 
    - cp php-Dockerfile Dockerfile
    - docker build -t "$PHP_IMAGE" .
    - docker push "$NGINX_IMAGE"
    - docker push "$PHP_IMAGE"
    - sed -i '/versionName/d' $JOB_STATE/php-image.env ; echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/php-image.env
    - sed -i '/versionName/d' $JOB_STATE/nginx-image.env ; echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/nginx-image.env
    - sed -i '/sourceName/d' $JOB_STATE/nginx-image.env ; echo "sourceName=$GCR_BASE/$NGINX_IMAGE_NAME" >> $JOB_STATE/nginx-image.env
    - sed -i '/sourceName/d' $JOB_STATE/php-image.env ; echo "sourceName=$GCR_BASE/$PHP_IMAGE_NAME" >> $JOB_STATE/php-image.env

######## INTEGRATIONS
integrations:
  hub:
    - integrationName: gcloud-integration    #replace with your subscription integration name
      type: gcloudKey

######## RESOURCES
resources:

######## IMAGES
  - name: nginx-image
    type: image
    integration: gcloud-integration    #replace with your Docker Hub integration name
    pointer:
      sourceName: $GCR_BASE/$NGINX_IMAGE_NAME  #replace with your image name on Docker Hub
    seed:
      versionName: "master.1"  #replace with your image tag on Docker Hub
    flags:
      - php-test-new

  - name: php-image
    type: image
    integration: gcloud-integration
    pointer:
      sourceName: $GCR_BASE/$PHP_IMAGE_NAME
    seed:
      versionName: "master.1"
    flags:
      - php-test-new

######### PARAMS
  - name: app_env_stage
    type: params
    version:
      params:
        SAMPLE_ENV_VAR: "hello-world"
        ENVIRONMENT: "stage"

  - name: app_env_prod
    type: params
    version:
      params:
        SAMPLE_ENV_VAR: "hello-world"
        ENVIRONMENT: "prod"

######### DOCKER OPTS
  - name: nginx_opts_stage
    type: dockerOptions
    version:
      memory: 32
      cpuShares: 10 # in millicores (200m = 0.2 CPU)
      labels:
        app: nginx
      portMappings:
        - ":80"

  - name: php_opts_stage
    type: dockerOptions
    version:
      memory: 32
      cpuShares: 10
      portMappings:
        - ":9000"

  - name: nginx_opts_prod
    type: dockerOptions
    version:
      memory: 64
      cpuShares: 20
      labels:
        app: nginx
      portMappings:
        - ":80"

  - name: php_opts_prod
    type: dockerOptions
    version:
      memory: 64
      cpuShares: 20
      portMappings:
        - ":9000"

######### REPLICAS
  - name: app_replicas_stage
    type: replicas
    version:
      count: 1

  - name: app_replicas_prod
    type: replicas
    version:
      count: 2

######### CLUSTERS 
  - name: gke-cluster_stage
    type: cluster
    integration: gcloud-integration    #replace with your Kubernetes integration name
    pointer:
      sourceName: "test-cluster"
      region: "europe-west1-d"
      namespace: "stage"
    flags:
     - php-test-new

  - name: gke-cluster_prod
    type: cluster
    integration: gcloud-integration    #replace with your Kubernetes integration name
    pointer:
      sourceName: "test-cluster"
      region: "europe-west1-d"
      namespace: "production"
    flags:
     - php-test-new

######### LOADBALANCERS
  - name: nginx-lb_stage
    type: loadBalancer
    integration: gcloud-integration 
    pointer:
      sourceName: nginx-lb
      method: NodePort
      namespace: "stage"
      clusterName: "test-cluster"
      region: "europe-west1-d"
    version:
      ports: 
        - name: http
          port: 80
          protocol: TCP
      selector:
        app: nginx

  - name: nginx-lb_prod
    type: loadBalancer
    integration: gcloud-integration
    pointer:
      sourceName: nginx-lb
      method: NodePort
      namespace: "production"
      clusterName: "test-cluster"
      region: "europe-west1-d"
    version:
      ports:
        - name: http
          port: 80
          protocol: TCP
      selector:
        app: nginx

######### KUBECTL CONFIG
  - name:           gcloud-cli
    type:           cliConfig
    integration:    gcloud-integration
    pointer:        
      region: "europe-west1-d"
      clusterName: "test-cluster"

######### JOBS
jobs:

######### CI
  - name: php-test-new_runCI
    type: runCI
    flags:
      - php-test-new
    steps:
      - OUT: nginx-image
      - OUT: php-image

######### MANIFEST
  - name: app-manifest_stage
    type: manifest
    flags:
      - php-test-new
    steps:
     - IN: php-image
     - IN: nginx-image
     - IN: app_env_stage
     - IN: nginx_opts_stage
       applyTo:
         - nginx-image
     - IN: php_opts_stage
       applyTo:
         - php-image

  - name: app-manifest_prod
    type: manifest
    flags:
      - php-test-new
    steps:
     - IN: php-image
     - IN: nginx-image
     - IN: app_env_prod
     - IN: nginx_opts_prod
       applyTo:
         - nginx-image
     - IN: php_opts_prod
       applyTo:
         - php-image

######### PROVISION
  - name: horizontal_pod_autoscaler
    type: runSh
    steps:
      - IN: deploy_prod
      - IN: gcloud-cli
        scopes:
          - gke
      - TASK:
        - script: "kubectl autoscale deployment deploy-prod-app-manifest-prod-$BUILD_NUMBER --min=1 --max=2 --cpu-percent=80"

  - name: provision_stage  
    type: provision
    steps:
      - IN: nginx-lb_stage  
      - IN: deploy_stage

  - name: provision_prod
    type: provision
    steps:
      - IN: nginx-lb_prod
      - IN: deploy_prod

######### DEPLOY
  - name: deploy_stage
    type: deploy
    flags:
      - php-test-new
    steps:
      - IN: app-manifest_stage
      - IN: gke-cluster_stage
      - IN: app_replicas_stage

  - name: deploy_prod
    type: deploy
    flags:
      - php-test-new
    steps:
      - IN: app-manifest_prod
        switch: off
      - IN: deploy_stage
        switch: off
      - IN: gke-cluster_prod
      - IN: app_replicas_prod
